### PR TITLE
debian packaging files

### PR DESCRIPTION
**Pull request by bmanojlovic**
This pull request adds debian packaging control files

### CODE REVIEW

**Comment by xadhoom** [comment]
thanks! I cannot test this because I don't use debian, but I'm sure they're ok :)

**Comment by bmanojlovic** [comment]
they work as i'm using them on my raspberry pi2 :)
http // naizvoru dot com

**Comment by xadhoom** [comment]
nice!

just for curiosity, how many channels can you transcode on the pi2?

**Comment by bmanojlovic** [comment]
i'm using it only with single channel as it is for my personal use so unfortunately can't give real numbers :(

**Comment by xadhoom** [comment]
ok, np! thanks again!

**Pull request merged**
